# Generated by Django 3.1.1 on 2020-09-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exceptions', '0002_auto_20200926_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptionmodel',
            name='error_codes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
